version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kalkulator
    volumes:
      - "./data:/var/lib/postgresql/data"